# Importing libraries and reading data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

# Displaying first five rows

In [3]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

# Displaying last five rows

In [4]:
df.tail()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
4595,2014-07-09 00:00:00,308166.666667,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,534333.333333,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,416904.166667,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,203400.000000,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,220600.000000,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

# Taking information from data

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(4), int64(9), object(5)
memory usage: 647.0+ KB

# There is no need of "date", "street", "city", "statezip", "country" column, so we remove it because it contains text data and machine learning model doesn't perform well on text data rather than numerical data

In [6]:
df = df.drop(["date","street","city","statezip","country"],axis=1)

In [7]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          4600 non-null   float64
 1   bedrooms       4600 non-null   float64
 2   bathrooms      4600 non-null   float64
 3   sqft_living    4600 non-null   int64
 4   sqft_lot       4600 non-null   int64
 5   floors         4600 non-null   float64
 6   waterfront     4600 non-null   int64
 7   view           4600 non-null   int64
 8   condition      4600 non-null   int64
 9   sqft_above     4600 non-null   int64
 10  sqft_basement  4600 non-null   int64
 11  yr_built       4600 non-null   int64
 12  yr_renovated   4600 non-null   int64
dtypes: float64(4), int64(9)
memory usage: 467.3 KB

# Assigning input variable

In [9]:
X = df.drop(["price"],axis=1)

# Assigning output variable

In [10]:
y = df["price"]

# Splitting data into training set and testing set

In [11]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
X_train.shape

(3680, 12)

In [13]:
X_test.shape

(920, 12)

In [14]:
y_train.shape

(3680,)

In [15]:
y_test.shape

(920,)

# Applying ML model

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
lg = LinearRegression()

In [18]:
lg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
y_pred = lg.predict(X_test)

In [20]:
print(y_test.values)

[  544000.              0.        1712500.         365000.
   275000.         625000.         453000.         300000.
   417985.714286   672500.         525000.         500000.
   590000.         305000.         210000.         915000.
   675000.         630000.        1690000.         883000.
  1700000.         612500.         615000.         590000.
   301500.          87500.         746000.         950100.
   415000.         775000.        3200000.         253000.
  1415000.         312891.         252000.         325000.
   455000.         540000.         215000.         653000.
   306000.         435000.         335000.         610000.
   245000.         365000.         260000.         615000.
  1250000.         835000.         490000.         482000.
   530000.         550000.         170000.         615000.
  1195000.         589950.         780000.         332000.
   850000.         700000.         230000.         966000.
   766950.         354000.         339000.         720000.
   349950.         246950.              0.         342500.
   292600.         736500.        1180500.         886000.
   860000.         569000.         235000.         358000.
   568500.         439000.         921000.         875000.
   325000.         206000.         409316.         452500.
   919204.         240000.         585000.         280000.
        0.         389000.         775950.        1384000.
   690000.         445000.         280000.         562000.
   680000.         560000.         280000.         431500.
   615000.         840000.         450000.         372220.
   520000.         515000.         542500.         790000.
   206000.         405000.         575000.         792000.
   505000.         545000.         700000.         616000.
   875000.              0.        1255000.         440000.
   839000.         500000.        1250000.         265000.
   613000.         330000.         235000.         310000.
   790000.         345000.         718000.         385000.
   345000.         375000.         705380.        1050000.
   427000.         288400.         465000.         374950.
   782000.         734200.         173666.666667   399950.
   195000.         380000.         259500.         730100.
   350000.         342000.         495000.         642000.
   870000.         293000.         613000.         253000.
   235000.         762000.         560000.         482000.
   588500.         350000.         799200.         141800.
   379900.         480000.         450385.714286   264500.
  1100000.         433111.111111   622500.         950833.333333
   424500.         866059.         449000.         236000.
   392000.         170500.         589000.         220600.
   256883.        2700000.         516200.         260000.
   496752.         260000.         815000.         230000.
   397000.         633000.         175000.        2400000.
  1140000.         507000.         325000.         140000.
   504200.         442000.         299000.         397500.
   435000.         350000.         679000.         567500.
   340000.        1225000.         542804.75       255000.
   720000.         471000.         309487.5        289987.5
   380000.         290000.         458000.         507000.
   999000.         804995.         330000.         620000.
   750000.         449950.         538000.         362000.
   548000.         835000.         209950.         415000.
   205425.         524000.         320000.         635000.
   600000.         472000.         225000.         469000.
   530000.         320000.         551000.         341000.
   390000.         400000.         232603.         390000.
   470000.         534333.333333   275000.         194000.
   310000.         300000.         255000.        1225000.
   339950.         520000.         451000.         450000.
   220000.         575000.         263900.         171224.8
   540000.         809000.         550000.         230000.
   210000.         300000.        1150000.         799000.
   288790.         455000.         440000.         306888.
   305000.         700000.         680000.         289950.
   563500.         210000.         560000.         245000.
   379950.         185000.         735000.         325000.
  2065000.         450000.         345000.         585000.
   350000.         850000.         363750.         695000.
   881000.         854000.         430000.         253779.
   540000.         367500.         276900.         540000.
   744500.         600000.         190000.         196440.
   510000.         690000.        2280000.        1228000.
  1370000.         828950.         895000.        1200000.
   210000.         335000.        1325000.         300000.
   411000.         468500.         440000.         490000.
   343000.         425000.         300000.         225000.
   559900.         583000.         499950.         480000.
   575000.         625000.         710000.         438000.
   700000.         770000.         250000.         692000.
   410000.         261350.         150000.         499950.
   925000.         326983.333333   550000.        1050000.
   160000.         205000.         290900.         252750.
  1365000.         342000.         280000.         235750.
   365000.         373000.         253000.         640000.
   450000.         581000.        1506000.         625000.
   567500.         845000.         965000.         772650.
   450000.         148226.         495000.         549900.
   335000.         367500.         512031.         678333.333333
   349000.         880000.         366750.         381000.
   535000.         717000.         239900.         499950.
   315000.         234000.         655000.         805000.
   373000.         394950.         275000.         380000.
   350000.         999000.         397000.         810000.
   500000.         672500.         445000.         292000.
   380000.         505000.         870000.         459950.
   675000.         419190.         597326.         325000.
   511555.         665000.         875000.        1050000.
   420850.         810000.         680000.         611000.
   455000.         635000.         278500.         175000.
   640000.         225000.         436110.         318000.
   645325.         235000.         830000.         270000.
   385000.         245000.         356000.         885000.
   341166.666667   429000.         275000.         800000.
   649950.         224000.         275000.         549000.
   425000.         584000.         413800.         481450.
   229800.         300000.         375000.         630000.
  2075000.        1710000.         515000.         775000.
   618250.         100000.         390000.         383962.
   445000.         555000.         331950.         530000.
   175000.         645000.         233000.         563500.
   280000.         955000.         540000.        1550000.
   404000.         625000.         325000.        1297000.
   225000.         427550.         425000.         735000.
   459990.        1735000.         248400.         425000.
   290000.        1065000.         980000.         645500.
   511000.         450000.         336000.         120000.
   510000.         500000.         640000.         565000.
   654950.         247200.         675000.         176400.
   600000.         699000.         382500.         345000.
   349900.         355000.         168000.         330000.
   635200.         799000.         385000.         513000.
   640000.         342000.         455000.         458000.
   879950.        1285000.         650000.         280000.
   325000.         575000.         345000.         670000.
   307000.         631625.         177500.         255000.
   492000.         339900.        1325000.         418000.
   324000.         466500.         190000.         558000.
   345000.         910000.         319950.         337000.
   712500.         660000.         320000.         310000.
   712198.         260000.         210000.         495000.
   302000.         769900.         402000.         750000.
   525000.         650000.         385000.         305000.
   712000.         795000.         195000.         470000.
   328000.         451000.         191000.         480000.
   283200.         320000.         445000.         629800.
   248000.         389999.        1395000.         850000.
        0.         313950.         744000.         550000.
   509900.         544000.         491234.         635000.
   700000.         820000.         720000.        2199900.
   347000.         326000.         439950.         549000.
   730001.         250000.         270000.         380000.
  1295648.         425000.         703000.        2150000.
   320000.         350000.         427874.         541125.
   333490.         350000.         390000.         332000.
   627000.         475000.         425000.         345000.
   450000.         527550.        1200000.         862500.
   754800.         374000.         295000.         437500.
   382500.         380680.555556   635700.         389000.
   552000.         925000.              0.        1532500.
   420000.         800000.        1220000.         710000.
 12899000.         285000.         430000.         950000.
  1510000.         610000.         484000.         303500.
   399895.         782000.         426500.         375000.
   735000.         250000.         605000.         740000.
   565000.         465000.         458400.         712000.
   345000.         200000.         485000.         437500.
  1695000.         725000.         242000.         732000.
   546000.         355000.         718500.         489000.
   348500.         215000.         715000.         175000.
   325000.         311100.         361280.         955500.
   623000.         427000.         298000.         404000.
        0.         495000.         640000.        1307000.
   308166.666667   492000.         755000.         355000.
   486000.         610000.         335000.         309950.
   619400.         595000.         600000.        1050000.
   400000.         160797.         427000.         437000.
   380000.         800000.         685000.        1025000.
   267345.         588000.         469950.         357186.
   565000.         391400.         255000.         373000.
   895000.              0.         525000.        1400000.
   880000.         723243.75       345000.         210000.
   557500.         575000.        1080000.         255000.
   417250.         200000.         150000.         639888.
   370000.         280000.         525888.         369500.
   330000.         800866.         925000.         663000.
   425000.         345000.         299950.         232500.
   148612.5        275000.         605000.         790000.
   499950.         599000.         791000.        1200000.
   200000.        1234582.         276900.         410000.
   375000.         349900.         325000.         471000.
   315000.         535800.         500000.         899000.
   240000.         405000.         245100.         225000.
   378750.         425000.         445800.         580000.
   370000.         850000.         210000.         388000.
   490000.         900000.         535000.         492000.
   870300.         265000.         539000.         560000.
   290300.        1298000.          83300.         309212.
   362750.         215000.         450000.         585000.
   139000.         485000.        1157400.         590000.
   375000.         647000.         716500.         395000.
   440000.         269950.         270000.         540000.
  1270000.         320000.         334000.         502000.
   255000.         668750.         650880.         309620.
   542525.         316850.         201500.         494815.
   540000.         530000.         555000.         570000.
   175000.        1750000.         243000.        2680000.
   580379.         945000.         333000.         245000.
   279900.         314500.         561000.         325000.
   340000.         247875.         619850.         499950.
   810000.        1014250.         270000.         460000.
   525000.         613000.         865000.         379950.
   423000.         459950.         608000.         377691.
   379000.         450000.         375000.         385000.
   240000.         415000.         615000.         860000.
   785000.         325000.         254000.         310000.
   218000.         300000.        1702500.         186950.
   337000.         370000.         400000.         415000.
  1200000.         305000.              0.         809000.
   225000.         385000.         770000.         868500.
   581000.         723000.         600000.         469000.
   237333.333333  1230000.         579000.         409124.
   975000.         325000.         239950.         659000.
   332000.         571986.111111   630000.         540000.
   259950.         308900.        1135250.         410000.
  1075000.        1216000.         664950.         825000.
   405000.         280500.         341000.         460000.
   438000.         272000.         947500.         224500.
   305000.         635000.         474900.         375000.
   250500.        1325000.         375000.         265050.
   571000.         254000.         288000.         395000.
   451000.         490000.         370000.         325000.
   506000.         613000.         485000.         498500.
   222400.         565000.         268000.         750000.
   230000.       26590000.         687000.         289659.      ]

In [21]:
print(y_pred)

[ 304863.38578062  326517.0699151  1071762.53630099  546241.40097356
  379799.98321081  605792.93622752  481263.57120655  418905.11058135
  509341.5079192   530852.97588252  682958.9764122   414525.36130057
  836974.4025991   416500.85730828  367263.43388221  702908.51672182
  677878.69067816  515539.32998703 1019380.63891406  861119.79490699
 1364866.21814691  637439.70016774  634739.56666342  470424.21250261
  162037.15383034  232831.37648238  669951.05071604  884080.66695005
  263027.22577201  974954.6422948  1883342.1639134   481510.29664856
 1275554.652537    430994.93178862  180366.40705413  339240.17357418
  792335.74094026 1011053.14613373  238036.20927675  543438.66040781
  423414.50597286  243429.92107968  390151.30073981  361322.67375665
  320343.34636012  317865.29287642  469559.60646623  573249.20158975
  828966.7569161   455286.46524109 1213320.90955274  379278.14711413
  456992.22261156  640657.04819536  281556.43960239  355542.07843766
  977771.43585351  763946.83314536 1012025.8315003   286955.28768717
  555835.61977618  928556.49045181  231280.25911123  910032.99943186
  769535.57238148  562525.11152536  637463.19873763  570860.0675127
  345837.01064873  295419.81242346 1006508.17902278  402155.24325434
  367461.91266225  870934.05572674  349348.42679601  763750.32849318
  540526.04457534  766712.7440783   477684.9361213   229401.15552787
  563785.76349423  309224.69194753  523372.99736624  826306.84346143
  359320.20890567  272129.52465176  384417.05303368  546211.65031796
  903097.91201919  320858.51775886  845866.14311463  285079.54355466
  304814.59399454  467565.73525602  650291.30744742 1143004.88154434
  724309.90300227  709038.64541326  453017.90997358  476379.49824263
  501727.98469165  380642.1312802   240381.51165494  461838.22853633
  481557.05182971  948783.75966196  660133.04579796  290276.9236583
  661221.23213629  583725.99937404  602486.70354448  575596.86113858
  294563.77075795  388805.64120467  995324.89932134  538263.87912053
  523482.0234596   679531.93989523  468848.01606422  355998.00959176
  713098.11614067  620513.40146249  734301.37951927  419909.42644168
  261870.25647557  309599.66817939  856156.96756062  462619.44780877
  316249.45792279  619234.91457489  410096.51028042  421977.58123597
  740906.84546311  368934.95325236  275512.17368784  339244.67408888
  326790.34090705  311169.82497176  607281.77186504  724274.31637022
  358795.31130752  438734.57557102  534109.63529714  347968.72983401
  962847.1589031   843264.6972412   247961.87220174  308624.05587786
  264645.83681693  295180.66112282  403004.70280149  715896.00537896
  709231.24879245  292807.56878761  762270.71401042  643055.17920438
 1258126.7534063   752499.84100212  401925.78179458  251971.95660316
  359391.79025315  940276.60823424  382562.36382343  615368.5138124
  515703.35748953  594174.02274643  842382.44396651  308053.10540569
  621516.05939243  735550.6236987   205470.86500573  466628.87635708
  873755.61292328  347428.26709868  687181.77023261  817197.54329574
  295237.22961944  663079.56797469  669745.66313072  334933.90721235
  445168.97222075  212192.27957855  710770.6694556   385172.09260551
  380602.41200775 1671266.35557865  693829.18041394  340391.76908039
  630592.15427284  427606.62802455  860962.99567359  234677.28552318
  236298.55856072  647974.51481868  513595.81813463 1495235.91491022
  795716.01922649  970101.04401531  236515.87861692  205976.17915485
  328649.24557339  599767.98478192  161623.58859484  591869.28189175
  464183.13480307  513400.24004997  626164.24935866  538041.36304031
  331152.31562663  816335.50787479  593225.64834883  389452.46780562
  880687.09269042  480694.10881641  557372.68907537  377656.62793017
  281998.24237934  349371.21341268  422950.87816746  353938.22060083
  710692.54097468  659093.1202777   254629.33523894  555123.39443182
  688125.60298332  547676.4195094   363317.10585675  334273.88910194
  548334.22184756  712203.51998896  248058.76456351  354194.65822134
  296171.3944182   451205.47091805  648109.36650126  709124.98888424
 1289448.47850991  290094.31038026  285637.30762794  353669.55744405
  544639.52794261  504083.08204836  565911.78776153  313289.58680411
  254998.67844751  570794.9109259   482032.66178425  551030.57171703
  371889.15542467  382199.67711401  243282.83298875  130162.34899394
  450633.50598173  372246.93314192  342553.2629112  1318129.04511715
  208538.80148275  793719.75475556  581609.08164076  358389.67813804
  162309.76012084  494467.57587958  344484.48489265  311498.37997764
  506684.53189411  572658.62918434  726223.66978096  364395.07224358
  386904.65865816  254419.20836791 1109090.23790824  719615.28030949
  260734.38055073  879122.19827609  394814.78468762  287963.16250525
  330188.20070809  580943.65958492  855375.07131326  313714.65770234
  394928.7959102   395230.54460015  537149.03037454  739095.60989221
  458637.48726435  302156.40348376  780449.53768584  551108.99056455
 1102977.66959438  247782.68424576  254673.92346335  529500.28656754
  441877.37621313  719485.84905132  364373.17508914  571174.15928881
  853680.36800746  689587.79264248  314072.87487035  512657.57817693
  365129.72029798  750378.49400229  471570.81639347  587779.09592335
  576120.83232984  585924.79061448  193553.31729771  282802.82264514
  452779.86505419  594246.25503801 3747679.54681628 1637256.81672999
 1156970.48270161 1012440.67347627  465966.64125342 1063456.65680833
  253833.22993091  465355.94092572  916081.52451197  378552.23503901
  563455.81196656  274346.45730105  471101.25387309  743148.406531
  437856.52021336  366734.60225414  288176.10983706  360667.87566561
  676203.79765287  443257.30987708  291244.43600938  643934.12121554
  356597.40770634  497350.94439291 1000109.24014718  173446.93487025
  463991.43529468  719851.84366783  419864.56440116 1322674.18477503
  367171.03653658  326407.9805427   327025.44358705  574144.59642676
  864845.06843277  299733.93861358  522813.83667066  838827.54109376
  424913.60827542  270486.46786436  601666.39623302  246626.78562442
 1149590.80227556  375392.6117726   393153.22563062  186187.20591469
  384061.37066557  614443.50208855  461418.19362064  657215.1092912
  586644.12171016  454716.25405976 1191021.35405112  331948.33304546
  557095.53793675  808895.11216751  723692.68778765  657688.13353309
  486897.57813303  292008.02496067  459382.5955671   619888.02588112
  442195.08900131  317122.36641296  555183.78623138  561550.11563753
  251622.13946968  760500.71657385  423722.54383677  501938.09602331
  454082.79868947  302931.17096728  258240.28348364  542860.05300292
  210332.7478981   610756.40027405  403275.82341811  942460.67673438
  415271.99064698  347858.20683404  274980.64283846  377943.79292618
  250048.03213685  640028.59543247  157075.20406856  849682.33005232
  519103.58432859  595184.22199735  487084.63915542  464384.74985927
  339817.78031657  251070.94564402 1059006.33313239  701917.8048069
  872187.48323685  390399.38512141  885843.88514457  592752.96795515
  341408.74905077  601939.54146391  496161.61052763  943525.70816052
  367671.4436026   639713.66557813  536447.13293788  563785.76349423
  260548.32023568  839482.02560403  427088.28242493  371895.31856825
  536735.95696345  231820.42689831  463428.77640915  595640.39146906
  655048.21685937  482140.45403893  720001.39109086  432373.52242796
  209601.71314218  217535.89123736  247114.74220654  659189.27343387
  510359.40600174  395408.14138147  501814.4195095   474163.985979
  525377.50228357  197801.93927661  195248.5351487   591958.34203958
  740908.2433814   282767.41384533  211823.83814549  391762.307045
  227033.43526083  279113.32962323  197157.96756657  647834.30994712
 1078736.16693833 1124705.06726569  607665.52684604  851471.06460997
  751128.93783347  228370.75656857  523876.23479939  605968.10671436
  380344.14038704  686998.77841015  686740.81455002  644735.12657221
  283788.42110727  494782.31740248  305715.52526105  631258.59508787
  286327.39219016 1399339.33495165  287934.50778439 1181722.01770646
  482445.99243706 1219255.61502806  196012.44451799  782289.61719243
  364224.0531878   270208.20855719  365058.35316168  619484.75777259
  650611.74396922 1350829.47252257  375964.11285467  498764.33812174
  385647.04549282 1073533.75667771  695307.72541532  699163.81065116
  412315.51777993  515599.06328154  705674.44705654  224159.83840017
  271908.28307511  369571.93930202  595511.1934798   385351.24662642
  663905.4218868   244908.11791612  328880.96337327  183321.67566968
  722011.39335946  578489.60575112  487853.52317457  425144.15791348
  669800.7147067   377376.57927225  326039.02948349  227931.41250219
  468966.96201676  737178.21852635  382908.13514472  421452.40136273
  455173.37253165  280856.84864574  322803.38329772  619440.34383022
 1107208.48055677  820744.9620932   565768.29278422  598069.80771146
  422687.90365995  376198.24111262  454250.1571572   707158.83528152
  349503.19206458  499190.71044376  247203.44497323  307664.50570907
  546731.1726019   261303.87521313  852754.41319643  188024.41745888
  166007.01266936  344981.27950155  324142.33681456  617064.36388174
  296989.58001435  883215.87144806  502834.28849114  516437.18671863
  413915.7666007   828985.14801782  542311.59275422  211889.11865772
  521709.45327643  377786.83526186  185313.66453015  442272.74877087
  230129.22956759  637630.80945177  316412.36182828  737837.77234156
  400185.2074042   787277.27746296  301076.50114969  426083.13018167
  680328.57409591  459497.35241736  257477.80806662  567695.09624891
  345116.48310123  655437.74907028  408280.0777241   412595.62049526
  411979.90858846  351688.06418113  331277.76218933  566054.18684607
  234632.20318683  302875.00818688 1119428.80942005  698512.27137044
 1993475.76057351  407263.11509429  673035.62345772  453782.23608868
  742215.65731279  636083.30377533  247035.67311498  586247.28280147
  686364.05476264  870113.76565066  734178.10569884  152280.93158772
  275319.36900451  170756.15040168  510259.96603915 1170826.09125815
  520995.51208308  375058.51151158  598509.4734877   485027.51532334
 1403645.47893119  329564.50636233  399175.43664426 1363505.56189649
  248513.0173247   217990.94513319  572958.57971696  632046.84570389
  446844.60744187  207164.54527018  657332.20091632  540277.97031736
  408359.19173812  237196.33315542  246311.03669665  337762.06474789
  476406.69721461  111892.43957017  616205.98030167  783059.80656614
  741518.17225652  581235.58878206  147165.15172821  833868.2037364
  252488.88520822  608341.17502825  752950.2429793   670980.11933524
  414935.59045333  769396.20666393  659035.60129101 1036037.28905247
  343547.28706976  662924.14231138 1124894.75877457  578427.59320658
  581325.53446141  371478.24742389  462867.58720097  927036.00272365
 1029377.72378009  621419.6459356   508290.5849316   199636.06108276
  574136.89802075  723026.19745101  630493.45353123  466079.14618309
  292846.01722576  216433.18296248  505298.49197981  705110.26595253
  759661.28701521  292604.15669842  532733.9482279   830041.94300547
  228557.45036849  282274.33048448  530715.37580348  522246.81152082
 1259473.1263276   575401.65476285  251800.09481379  521708.46409724
  365554.91847645  559232.1409843  1009468.02423337 1018713.38089434
  302358.62782872  226740.07061441  811408.81880636  205034.45022674
  552251.99666768  450440.23413976  254571.06512046  623372.21794518
  427167.83917256  672649.54728202  436908.07951071  383810.94914882
  587737.36261515  481917.83620937  564368.76706422  809845.24131528
  403347.60829373 1007160.8663426   871843.37304363  442808.65832651
  896592.95932318  952415.03154821  373549.12635201  492945.04062967
  628450.49126525  458602.13956396  356838.91588734  509086.21139681
  540767.2736007   219302.95494363  347809.98212761  272430.34180469
  437593.3448249   777175.2324948   589499.03455769 1094978.54029041
  569596.58083948  713306.193302    573586.56484184  255701.56701581
  513874.51083601  264901.72924131  204029.18248279  551974.63545403
  762792.64177462 1069710.75246011  391012.10326702  785447.22518783
  930912.33055828  669289.76822304  526907.22933073  288643.23577349
  482018.81225702  631706.18485565 1348334.51405377  417903.59354914
  403955.56695891  227709.35737838  279148.68383137  411782.2539066
  209265.95028704  481603.36967418  526775.50167795  409952.73235539
  439374.76789913  731361.96941413  684082.47745302 1172875.89432581
  273366.49819544  428810.57813981  214372.73112984  453033.48306787
  314216.42114382  420374.03169884  723958.12673496  822837.28415966
  731468.36851871  609406.64696124  611793.62488995  688733.2742999
  681762.18778141 1065349.2030804   297103.86193507  332247.12526373
  745500.00331321  390927.57834859  564742.29195181  497650.33688509
  439224.28290039  398245.13435283  458158.74008711  449872.16725994
  451512.1362437   317880.64265943  189527.5513075   523752.3474544
  730907.19713395  438402.63186132  405697.55438087  440466.89990902
  614293.96768515  500312.13216878  212278.31196112  552883.87990067
  505993.57831123 1090940.49167456  590481.29207448  811916.69471939
  732082.51068671  422220.86449565  381450.02626046  495726.99591288
  300586.02769093  731207.2591241   323105.24199343  206557.53757115
  522373.40014485  423157.22820225  607631.068898    565341.41966392
  239878.30618137  395192.19208276 1014385.79095899  458064.15375093
  286420.01056186  707353.15874711  770590.41636125  346452.8236616
  407177.93996258  438622.4170473   326124.69645469  493028.746084
  742347.39120428  208569.52019586  603189.05322258  407490.15341507
  548954.27809992  629929.58671676  718038.54039656  422033.88099448
  559142.59869438  939694.24046505  436509.45312407  416091.24987756
  493859.67986316  452502.96341011  511344.48186192  502954.30074428
  189919.11869074 1049783.5652136   429429.51240616 1073083.64634391
  549354.19381626  685795.32141673  438452.32326619  300327.24977437
  306503.96568311  494572.38644204  614943.88943398  632946.43077657
  466775.63646368  327839.87606082  540604.40806974  253640.62359123
  605881.41221696  543573.58649245  372413.3110136   626564.46219489
  695932.9190572   481487.14080824  623348.58302448  418005.10061232
  486333.74660194  403250.65944124  551683.32157233  470596.60900457
  409705.47933978  487171.27666     429399.82354236  795663.57590408
  374614.85483607  242723.18025058  526581.8420093   895632.59905976
  721051.36373876  183051.24800145  317383.44189464  434292.15172849
  202260.0822135   482438.47805349 1438549.68519819  387557.39871495
  272302.35815227  367149.26449774  746281.50899869  294578.95302319
  749374.76454814  571109.00346623 1027484.81513776  688892.94908777
  257603.94595989  410116.18009739  763952.45809241  786118.55893854
  437893.46845438  448894.43105809  804849.87659589  298325.17123474
  744258.66769607  702156.70288081  407295.81456184  770061.56305947
  517327.12820046  489944.87863217  537898.75504607  629907.13303498
  493438.2728113  1005476.0723024  1172173.17170566  818304.01046911
  437167.20455059  560987.6486534  1817981.50124277  567263.71967372
 1400693.71486613  942608.05094324  693081.86931324  658655.30098255
  215440.25102772  387105.64373943  380651.24542518  356214.48396375
  386769.36098996  239522.60677345  840218.5110131   231860.95819458
  605757.48664887  755726.61119957  428056.74091409  471230.69752611
  434741.68613769  693878.4748936   468624.55671958  145438.01384811
  691853.23131633  300997.05757008  347219.69148185  380242.76377125
  306188.05833553  620037.49492279  204081.11703555  337110.09771371
  539724.99797526  515774.23716576  524134.14632034  645273.58209344
  172108.58086366  507750.25915009  410029.16268317  443131.18231229
  441322.09004182  204405.45392689  659612.42309008  545264.71316852]

# Saving the model

In [22]:
import pickle

file = open("house.pkl","wb")
pickle.dump(lg,file)
file.close()